### ISSUE TITLE
master detay ekranarda detay gridde insert yaptıgımızda fridin satırı direk açılmıyor

### ISSUE THREAD

**Issue by ibrahimozdemir** [selamialtin/anamar_erp#13]
master detay ekranarda detay gridde insert yaptıgımızda fridin satırı direk açılmıyor. Mutlaka gridin o satırında çift tıklatınca satır açılıyor.

**Comment by selamialtin** [comment]
İlk focus olan alan visible değilse o şekilde kalıyor, kendo bug'ı kendoya support açılacak, şimdilik sütun sıralaması değiştirilerek çözülebilir, visible hide olacak alanları sona taşıdım, şuanda bu şekilde kullanabiliriz.
