### ISSUE TITLE
personel ekranında tipi "kadro" iken "Taseron"  yaptıgımızda organization_id bir degere sahip olmalıdır hatası geliyor.

### ISSUE THREAD

**Issue by ibrahimozdemir** [selamialtin/anamar_erp#20]
* Aslında bu durumda PersonnelSubCon tablosuna insert etmesi gerekiyor. Ama organisaiton hatası geliyor.
* Ek olarak, bu hata oluşmasına ragmen son kullanıcıya hata  mesajı dönmüyor. yani kullanıcı kaydettiğini zannediyor.
* Ayrıca ekranda hem taşeron hem de organizasyon sekmeleri görünüyor.

![image](https://cloud.githubusercontent.com/assets/9247438/5694484/03149af8-9967-11e4-9b8c-30a78003ec6c.png)

**Comment by selamialtin** [comment]
organisation_id normalde kalktı, büyük ihtimalle senin veritabanın eski versiyonda kalmış, organisation_id alanı hala veritabanında ve notnull durumda o yüzden bu hatayı alıyorsun.
