### ISSUE TITLE
domain constraitlerdeki hata mesajlarının değişken kısımlarının da lokazitiondan gelmesi

### ISSUE THREAD

**Issue by ibrahimozdemir** [selamialtin/anamar_erp#31]
![image](https://cloud.githubusercontent.com/assets/9247438/5798785/b274a7dc-9fd3-11e4-9cf3-76ac7e102894.png)

**Comment by selamialtin** [comment]
dil dosyasına com.anamar.hr.Organization eklenirse oradan dil dosyasından alıyor, property de aynı şekilde 
com.anamar.hr.Organization.finishDate eklenirse oda lokalize oluyor. biz dil dosyasını name space ler olamdan yaptık ya tüm field ve nesneleri namespace ile birlikte yeniden gireceğiz yada ekranları değiştirip hepsinini namespace li hale getiireceğiz.

**Comment by ibrahimozdemir** [comment]
com.anamar.hr.Organisation  olarak eklemiştim. Ama olmayınca açmıştım.

**Comment by selamialtin** [comment]
Dokumaninda o sekilde yaziyor bende denemedim henuz, deneyip donus yaparim
