### ISSUE TITLE
hatalı i18 kodu custom.errors.noData 

### ISSUE THREAD

**Issue by selamialtin** [selamialtin/anamar_erp#35]
custom.errors.noData kodunda açıklama olarak özel bir durumu göstermekte (Aktif Organizasyon veya Taşeron Bilgisi Bulunamadı), bu tarz kodların daha belirgin bir isimle belirtilmesi hatta sadece ilgili olduğu namespace yada domain altına alınması daha doğru olacak diye düşünüyorum

hr.personnel.noActiveOrgOrSubcon  gibi.

**Comment by ibrahimozdemir** [comment]
hr.personnel.msg.noActiveOrgOrSubcon desek nasıl olur. en azından msglar belirgin olur

**Comment by selamialtin** [comment]
ok
