### ISSUE TITLE
Form ekranında "RELOAD" butonuna basılınca tablar kayboluyor

### ISSUE THREAD

**Issue by ibrahimozdemir** [selamialtin/anamar_erp#5]
Form ekranında "RELOAD" butonuna basılınca tablar kayboluyor. tüm gridler alt alta çıkıyor

**Comment by selamialtin** [comment]
Detay tab kurgusu değiştiriken arada commit yapmıştım, ondan kaynaklı son revizyonda dügün çalışıyor.
